// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjdzrttanzlafyuwgiuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZHpydHRhbnpsYWZ5dXdnaXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzAyOTMsImV4cCI6MjA2ODM0NjI5M30.QVvsAjkJk2Re8CITn05uDrepzLBL1W77z_Hz3EzMYSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});